FROM node:alpine

# Create app directory
WORKDIR /usr/src/app
RUN chmod -R 777 /usr/src/app

# install git
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

# Install app dependencies
COPY ./package.json .
RUN npm install

WORKDIR /home/node
COPY ./docker/entrypoint.sh .

EXPOSE 8080
# CMD tail -f /dev/null
CMD ./entrypoint.sh /usr/src/app
